/* SPDX-License-Identifier: GPL-3.0-or-later */
#ifndef JAGLINK_DISCOVER_H
#define JAGLINK_DISCOVER_H

#include "link/discover.h"

typedef link_safety_decision jaglink_safety_decision;
#define JAGLINK_SAFETY_BLOCK LINK_SAFETY_BLOCK
#define JAGLINK_SAFETY_ALLOW_READ_ONLY LINK_SAFETY_ALLOW_READ_ONLY

typedef link_safety_reason jaglink_safety_reason;
#define JAGLINK_SAFETY_REASON_ALLOWED_OBD_READ LINK_SAFETY_REASON_ALLOWED_OBD_READ
#define JAGLINK_SAFETY_REASON_ALLOWED_UDS_READ LINK_SAFETY_REASON_ALLOWED_UDS_READ
#define JAGLINK_SAFETY_REASON_EMPTY_REQUEST LINK_SAFETY_REASON_EMPTY_REQUEST
#define JAGLINK_SAFETY_REASON_WRITE_OR_CONTROL LINK_SAFETY_REASON_WRITE_OR_CONTROL
#define JAGLINK_SAFETY_REASON_ECU_RESET LINK_SAFETY_REASON_ECU_RESET
#define JAGLINK_SAFETY_REASON_SECURITY_ACCESS LINK_SAFETY_REASON_SECURITY_ACCESS
#define JAGLINK_SAFETY_REASON_ROUTINE_CONTROL LINK_SAFETY_REASON_ROUTINE_CONTROL
#define JAGLINK_SAFETY_REASON_DTC_CLEAR LINK_SAFETY_REASON_DTC_CLEAR
#define JAGLINK_SAFETY_REASON_PROGRAMMING LINK_SAFETY_REASON_PROGRAMMING
#define JAGLINK_SAFETY_REASON_DENY_BY_DEFAULT LINK_SAFETY_REASON_DENY_BY_DEFAULT

typedef link_safety_result jaglink_safety_result;
#define jaglink_safety_classify link_safety_classify
#define jaglink_safety_reason_string link_safety_reason_string

typedef link_evidence_writer jaglink_evidence_writer;
#define jaglink_evidence_open link_evidence_open
#define jaglink_evidence_write_frame link_evidence_write_frame
#define jaglink_evidence_write_annotation link_evidence_write_annotation
#define jaglink_evidence_flush link_evidence_flush
#define jaglink_evidence_close link_evidence_close

#endif
