// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * @file isotp.h
 * @brief JAGLINK compatibility facade for LINK-owned ISO-TP.
 */
#ifndef JAGLINK_ISOTP_H
#define JAGLINK_ISOTP_H

#include "link/isotp.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LinkIsoTpAddressingMode JaglinkIsoTpAddressingMode;
typedef LinkIsoTpTargetType JaglinkIsoTpTargetType;
typedef LinkIsoTpFlowStatus JaglinkIsoTpFlowStatus;
typedef LinkIsoTpResult JaglinkIsoTpResult;
typedef LinkIsoTpRxState JaglinkIsoTpRxState;
typedef LinkIsoTpTxState JaglinkIsoTpTxState;
typedef LinkIsoTpAddress JaglinkIsoTpAddress;
typedef LinkIsoTpCanFrame JaglinkIsoTpCanFrame;
typedef LinkIsoTpRxConfig JaglinkIsoTpRxConfig;
typedef LinkIsoTpRx JaglinkIsoTpRx;
typedef LinkIsoTpTxConfig JaglinkIsoTpTxConfig;
typedef LinkIsoTpTx JaglinkIsoTpTx;

#define JAGLINK_ISOTP_CLASSIC_CAN_DATA_LENGTH LINK_ISOTP_CLASSIC_CAN_DATA_LENGTH
#define JAGLINK_ISOTP_CAN_FD_MAX_DATA_LENGTH LINK_ISOTP_CAN_FD_MAX_DATA_LENGTH
#define JAGLINK_ISOTP_MAX_PDU_LENGTH LINK_ISOTP_MAX_PDU_LENGTH

#define JAGLINK_ISOTP_ADDRESSING_NORMAL LINK_ISOTP_ADDRESSING_NORMAL
#define JAGLINK_ISOTP_ADDRESSING_EXTENDED LINK_ISOTP_ADDRESSING_EXTENDED
#define JAGLINK_ISOTP_ADDRESSING_MIXED LINK_ISOTP_ADDRESSING_MIXED

#define JAGLINK_ISOTP_TARGET_PHYSICAL LINK_ISOTP_TARGET_PHYSICAL
#define JAGLINK_ISOTP_TARGET_FUNCTIONAL LINK_ISOTP_TARGET_FUNCTIONAL

#define JAGLINK_ISOTP_FLOW_CONTINUE_TO_SEND LINK_ISOTP_FLOW_CONTINUE_TO_SEND
#define JAGLINK_ISOTP_FLOW_WAIT LINK_ISOTP_FLOW_WAIT
#define JAGLINK_ISOTP_FLOW_OVERFLOW LINK_ISOTP_FLOW_OVERFLOW

#define JAGLINK_ISOTP_RESULT_OK LINK_ISOTP_RESULT_OK
#define JAGLINK_ISOTP_RESULT_COMPLETE LINK_ISOTP_RESULT_COMPLETE
#define JAGLINK_ISOTP_RESULT_WAIT_FLOW_CONTROL LINK_ISOTP_RESULT_WAIT_FLOW_CONTROL
#define JAGLINK_ISOTP_RESULT_WAIT_SEPARATION LINK_ISOTP_RESULT_WAIT_SEPARATION
#define JAGLINK_ISOTP_RESULT_FLOW_CONTROL_WAIT LINK_ISOTP_RESULT_FLOW_CONTROL_WAIT
#define JAGLINK_ISOTP_RESULT_INVALID_ARGUMENT LINK_ISOTP_RESULT_INVALID_ARGUMENT
#define JAGLINK_ISOTP_RESULT_INVALID_FRAME LINK_ISOTP_RESULT_INVALID_FRAME
#define JAGLINK_ISOTP_RESULT_UNEXPECTED_FRAME LINK_ISOTP_RESULT_UNEXPECTED_FRAME
#define JAGLINK_ISOTP_RESULT_WRONG_SEQUENCE LINK_ISOTP_RESULT_WRONG_SEQUENCE
#define JAGLINK_ISOTP_RESULT_BUFFER_TOO_SMALL LINK_ISOTP_RESULT_BUFFER_TOO_SMALL
#define JAGLINK_ISOTP_RESULT_PAYLOAD_TOO_LARGE LINK_ISOTP_RESULT_PAYLOAD_TOO_LARGE
#define JAGLINK_ISOTP_RESULT_TIMEOUT LINK_ISOTP_RESULT_TIMEOUT
#define JAGLINK_ISOTP_RESULT_FLOW_CONTROL_OVERFLOW LINK_ISOTP_RESULT_FLOW_CONTROL_OVERFLOW
#define JAGLINK_ISOTP_RESULT_WAIT_FRAME_LIMIT LINK_ISOTP_RESULT_WAIT_FRAME_LIMIT
#define JAGLINK_ISOTP_RESULT_UNSUPPORTED LINK_ISOTP_RESULT_UNSUPPORTED

#define JAGLINK_ISOTP_RX_IDLE LINK_ISOTP_RX_IDLE
#define JAGLINK_ISOTP_RX_RECEIVING LINK_ISOTP_RX_RECEIVING
#define JAGLINK_ISOTP_RX_COMPLETE LINK_ISOTP_RX_COMPLETE
#define JAGLINK_ISOTP_RX_FAILED LINK_ISOTP_RX_FAILED

#define JAGLINK_ISOTP_TX_IDLE LINK_ISOTP_TX_IDLE
#define JAGLINK_ISOTP_TX_WAIT_FLOW_CONTROL LINK_ISOTP_TX_WAIT_FLOW_CONTROL
#define JAGLINK_ISOTP_TX_SENDING LINK_ISOTP_TX_SENDING
#define JAGLINK_ISOTP_TX_COMPLETE LINK_ISOTP_TX_COMPLETE
#define JAGLINK_ISOTP_TX_FAILED LINK_ISOTP_TX_FAILED

#define jaglink_isotp_result_name link_isotp_result_name
#define jaglink_isotp_rx_state_name link_isotp_rx_state_name
#define jaglink_isotp_tx_state_name link_isotp_tx_state_name
#define jaglink_isotp_address_is_valid link_isotp_address_is_valid
#define jaglink_isotp_can_data_length_is_valid link_isotp_can_data_length_is_valid
#define jaglink_isotp_stmin_to_us link_isotp_stmin_to_us
#define jaglink_isotp_rx_init link_isotp_rx_init
#define jaglink_isotp_rx_reset link_isotp_rx_reset
#define jaglink_isotp_rx_feed link_isotp_rx_feed
#define jaglink_isotp_rx_tick link_isotp_rx_tick
#define jaglink_isotp_rx_payload link_isotp_rx_payload
#define jaglink_isotp_tx_init link_isotp_tx_init
#define jaglink_isotp_tx_reset link_isotp_tx_reset
#define jaglink_isotp_tx_start link_isotp_tx_start
#define jaglink_isotp_tx_accept_flow_control link_isotp_tx_accept_flow_control
#define jaglink_isotp_tx_next link_isotp_tx_next
#define jaglink_isotp_tx_tick link_isotp_tx_tick

#ifdef __cplusplus
}
#endif

#endif
