// SPDX-License-Identifier: GPL-3.0-or-later
#ifndef JAGLINK_SCHEDULER_H
#define JAGLINK_SCHEDULER_H

#include "jaglink/obd2.h"
#include "jaglink/parameter.h"
#include "link/scheduler.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LinkSchedulerPriority JaglinkSchedulerPriority;
typedef LinkSchedulerResult JaglinkSchedulerResult;
typedef LinkSchedulerNextResult JaglinkSchedulerNextResult;
typedef LinkSchedulerItem JaglinkSchedulerItem;
typedef LinkScheduler JaglinkScheduler;
typedef LinkSchedulerDispatch JaglinkSchedulerDispatch;

#define JAGLINK_SCHEDULER_MAX_ITEMS LINK_SCHEDULER_MAX_ITEMS
#define JAGLINK_SCHEDULER_PRIORITY_LOW LINK_SCHEDULER_PRIORITY_LOW
#define JAGLINK_SCHEDULER_PRIORITY_NORMAL LINK_SCHEDULER_PRIORITY_NORMAL
#define JAGLINK_SCHEDULER_PRIORITY_HIGH LINK_SCHEDULER_PRIORITY_HIGH
#define JAGLINK_SCHEDULER_PRIORITY_CRITICAL LINK_SCHEDULER_PRIORITY_CRITICAL
#define JAGLINK_SCHEDULER_RESULT_OK LINK_SCHEDULER_RESULT_OK
#define JAGLINK_SCHEDULER_RESULT_INVALID_ARGUMENT LINK_SCHEDULER_RESULT_INVALID_ARGUMENT
#define JAGLINK_SCHEDULER_RESULT_FULL LINK_SCHEDULER_RESULT_FULL
#define JAGLINK_SCHEDULER_RESULT_DUPLICATE LINK_SCHEDULER_RESULT_DUPLICATE
#define JAGLINK_SCHEDULER_RESULT_NOT_FOUND LINK_SCHEDULER_RESULT_NOT_FOUND
#define JAGLINK_SCHEDULER_NEXT_READY LINK_SCHEDULER_NEXT_READY
#define JAGLINK_SCHEDULER_NEXT_WAITING LINK_SCHEDULER_NEXT_WAITING
#define JAGLINK_SCHEDULER_NEXT_PAUSED LINK_SCHEDULER_NEXT_PAUSED
#define JAGLINK_SCHEDULER_NEXT_EMPTY LINK_SCHEDULER_NEXT_EMPTY
#define JAGLINK_SCHEDULER_NEXT_INVALID_ARGUMENT LINK_SCHEDULER_NEXT_INVALID_ARGUMENT

#define jaglink_scheduler_result_name link_scheduler_result_name
#define jaglink_scheduler_next_result_name link_scheduler_next_result_name
#define jaglink_scheduler_init link_scheduler_init
#define jaglink_scheduler_add_parameter link_scheduler_add_parameter
#define jaglink_scheduler_set_parameter_enabled link_scheduler_set_parameter_enabled
#define jaglink_scheduler_add link_scheduler_add
#define jaglink_scheduler_set_enabled link_scheduler_set_enabled
#define jaglink_scheduler_set_paused link_scheduler_set_paused
#define jaglink_scheduler_next link_scheduler_next
#define jaglink_scheduler_mark_dispatched link_scheduler_mark_dispatched

JaglinkSchedulerResult jaglink_scheduler_configure_standard_obd2(
    JaglinkScheduler *scheduler,
    const JaglinkObd2PidSet *supported,
    uint64_t first_due_ms);

#ifdef __cplusplus
}
#endif
#endif
