// SPDX-License-Identifier: GPL-3.0-or-later
#ifndef JAGLINK_TELEMETRY_H
#define JAGLINK_TELEMETRY_H

#include "jaglink/elm327.h"
#include "jaglink/obd2.h"
#include "link/telemetry.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LinkTelemetrySample JaglinkTelemetrySample;
typedef LinkTelemetryTranscriptEntry JaglinkTelemetryTranscriptEntry;
typedef LinkTelemetryStore JaglinkTelemetryStore;
typedef LinkTelemetrySessionMetadata JaglinkTelemetrySessionMetadata;
typedef LinkTelemetryTextSink JaglinkTelemetryTextSink;
typedef LinkTelemetryRecorder JaglinkTelemetryRecorder;

#define JAGLINK_TELEMETRY_HISTORY_CAPACITY LINK_TELEMETRY_HISTORY_CAPACITY
#define JAGLINK_TELEMETRY_ADAPTER_TEXT_LENGTH LINK_TELEMETRY_ADAPTER_TEXT_LENGTH
#define JAGLINK_TELEMETRY_VEHICLE_TEXT_LENGTH LINK_TELEMETRY_VEHICLE_TEXT_LENGTH
#define JAGLINK_TELEMETRY_TRANSCRIPT_CAPACITY LINK_TELEMETRY_TRANSCRIPT_CAPACITY
#define JAGLINK_TELEMETRY_TRANSCRIPT_COMMAND_LENGTH LINK_TELEMETRY_TRANSCRIPT_COMMAND_LENGTH
#define JAGLINK_TELEMETRY_TRANSCRIPT_RESPONSE_LENGTH LINK_TELEMETRY_TRANSCRIPT_RESPONSE_LENGTH

#define jaglink_telemetry_store_init link_telemetry_store_init
#define jaglink_telemetry_store_clear_samples link_telemetry_store_clear_samples
#define jaglink_telemetry_store_latest link_telemetry_store_latest
#define jaglink_telemetry_store_history_count link_telemetry_store_history_count
#define jaglink_telemetry_store_total_sample_count link_telemetry_store_total_sample_count
#define jaglink_telemetry_store_history_at link_telemetry_store_history_at
#define jaglink_telemetry_store_set_favourite link_telemetry_store_set_favourite
#define jaglink_telemetry_store_is_favourite link_telemetry_store_is_favourite
#define jaglink_telemetry_store_transcript_count link_telemetry_store_transcript_count
#define jaglink_telemetry_store_transcript_at link_telemetry_store_transcript_at
#define jaglink_telemetry_session_metadata_init link_telemetry_session_metadata_init
#define jaglink_telemetry_session_metadata_set_adapter link_telemetry_session_metadata_set_adapter
#define jaglink_telemetry_session_metadata_set_vehicle link_telemetry_session_metadata_set_vehicle
#define jaglink_telemetry_session_metadata_finish link_telemetry_session_metadata_finish
#define jaglink_telemetry_recorder_init link_telemetry_recorder_init
#define jaglink_telemetry_recorder_finish link_telemetry_recorder_finish

bool jaglink_telemetry_store_record(JaglinkTelemetryStore *store, uint64_t timestamp_ms, const JaglinkObd2Sample *measurement);
bool jaglink_telemetry_store_record_transcript(JaglinkTelemetryStore *store, uint64_t timestamp_ms, const char *command, const JaglinkElm327Response *response);
bool jaglink_telemetry_recorder_begin(JaglinkTelemetryRecorder *recorder, const JaglinkTelemetrySessionMetadata *metadata, JaglinkTelemetryTextSink sink, void *context);
bool jaglink_telemetry_recorder_continue(JaglinkTelemetryRecorder *recorder, const JaglinkTelemetrySessionMetadata *metadata, JaglinkTelemetryTextSink sink, void *context);
bool jaglink_telemetry_recorder_record_sample(JaglinkTelemetryRecorder *recorder, const JaglinkTelemetrySample *sample, bool favourite);
bool jaglink_telemetry_recorder_record_response(JaglinkTelemetryRecorder *recorder, uint64_t timestamp_ms, const char *command, const JaglinkElm327Response *response);
bool jaglink_telemetry_export_csv(const JaglinkTelemetryStore *store, const JaglinkTelemetrySessionMetadata *metadata, JaglinkTelemetryTextSink sink, void *context);

#ifdef __cplusplus
}
#endif
#endif
