// SPDX-License-Identifier: GPL-3.0-or-later
/**
 * @file uds.h
 * @brief JAGLINK compatibility aliases for LINK's shared ISO 14229 UDS engine.
 */
#ifndef JAGLINK_UDS_H
#define JAGLINK_UDS_H

#include "link/uds.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef LinkUdsResult JaglinkUdsResult;
typedef LinkUdsResponseKind JaglinkUdsResponseKind;
typedef LinkUdsResponse JaglinkUdsResponse;
typedef LinkUdsSessionResponse JaglinkUdsSessionResponse;
typedef LinkUdsDidRecord JaglinkUdsDidRecord;
typedef LinkUdsDidDefinition JaglinkUdsDidDefinition;
typedef LinkUdsDidValue JaglinkUdsDidValue;
typedef LinkUdsClientConfig JaglinkUdsClientConfig;
typedef LinkUdsClientState JaglinkUdsClientState;
typedef LinkUdsClient JaglinkUdsClient;

#define JAGLINK_UDS_SERVICE_DIAGNOSTIC_SESSION_CONTROL LINK_UDS_SERVICE_DIAGNOSTIC_SESSION_CONTROL
#define JAGLINK_UDS_SERVICE_READ_DATA_BY_IDENTIFIER LINK_UDS_SERVICE_READ_DATA_BY_IDENTIFIER
#define JAGLINK_UDS_SERVICE_TESTER_PRESENT LINK_UDS_SERVICE_TESTER_PRESENT
#define JAGLINK_UDS_SERVICE_NEGATIVE_RESPONSE LINK_UDS_SERVICE_NEGATIVE_RESPONSE
#define JAGLINK_UDS_SESSION_DEFAULT LINK_UDS_SESSION_DEFAULT
#define JAGLINK_UDS_SESSION_PROGRAMMING LINK_UDS_SESSION_PROGRAMMING
#define JAGLINK_UDS_SESSION_EXTENDED LINK_UDS_SESSION_EXTENDED
#define JAGLINK_UDS_SESSION_SAFETY_SYSTEM LINK_UDS_SESSION_SAFETY_SYSTEM
#define JAGLINK_UDS_NRC_RESPONSE_PENDING LINK_UDS_NRC_RESPONSE_PENDING
#define JAGLINK_UDS_RESULT_OK LINK_UDS_RESULT_OK
#define JAGLINK_UDS_RESULT_COMPLETE LINK_UDS_RESULT_COMPLETE
#define JAGLINK_UDS_RESULT_WAITING LINK_UDS_RESULT_WAITING
#define JAGLINK_UDS_RESULT_RESPONSE_PENDING LINK_UDS_RESULT_RESPONSE_PENDING
#define JAGLINK_UDS_RESULT_NEGATIVE_RESPONSE LINK_UDS_RESULT_NEGATIVE_RESPONSE
#define JAGLINK_UDS_RESULT_INVALID_ARGUMENT LINK_UDS_RESULT_INVALID_ARGUMENT
#define JAGLINK_UDS_RESULT_BUFFER_TOO_SMALL LINK_UDS_RESULT_BUFFER_TOO_SMALL
#define JAGLINK_UDS_RESULT_MALFORMED_PDU LINK_UDS_RESULT_MALFORMED_PDU
#define JAGLINK_UDS_RESULT_UNEXPECTED_RESPONSE LINK_UDS_RESULT_UNEXPECTED_RESPONSE
#define JAGLINK_UDS_RESULT_BUSY LINK_UDS_RESULT_BUSY
#define JAGLINK_UDS_RESULT_TIMEOUT LINK_UDS_RESULT_TIMEOUT
#define JAGLINK_UDS_RESULT_FAILED_STATE LINK_UDS_RESULT_FAILED_STATE
#define JAGLINK_UDS_RESULT_UNSUPPORTED LINK_UDS_RESULT_UNSUPPORTED
#define JAGLINK_UDS_RESPONSE_POSITIVE LINK_UDS_RESPONSE_POSITIVE
#define JAGLINK_UDS_RESPONSE_NEGATIVE LINK_UDS_RESPONSE_NEGATIVE
#define JAGLINK_UDS_CLIENT_IDLE LINK_UDS_CLIENT_IDLE
#define JAGLINK_UDS_CLIENT_WAITING_RESPONSE LINK_UDS_CLIENT_WAITING_RESPONSE
#define JAGLINK_UDS_CLIENT_RESPONSE_PENDING LINK_UDS_CLIENT_RESPONSE_PENDING
#define JAGLINK_UDS_CLIENT_COMPLETE LINK_UDS_CLIENT_COMPLETE
#define JAGLINK_UDS_CLIENT_FAILED LINK_UDS_CLIENT_FAILED

#define jaglink_uds_result_name link_uds_result_name
#define jaglink_uds_client_state_name link_uds_client_state_name
#define jaglink_uds_negative_response_code_name link_uds_negative_response_code_name
#define jaglink_uds_decode_response link_uds_decode_response
#define jaglink_uds_build_session_control_request link_uds_build_session_control_request
#define jaglink_uds_decode_session_control_response link_uds_decode_session_control_response
#define jaglink_uds_build_tester_present_request link_uds_build_tester_present_request
#define jaglink_uds_decode_tester_present_response link_uds_decode_tester_present_response
#define jaglink_uds_build_read_did_request link_uds_build_read_did_request
#define jaglink_uds_decode_read_did_response link_uds_decode_read_did_response
#define jaglink_uds_did_definition_is_valid link_uds_did_definition_is_valid
#define jaglink_uds_build_defined_did_request link_uds_build_defined_did_request
#define jaglink_uds_decode_defined_did_response link_uds_decode_defined_did_response
#define jaglink_uds_client_init link_uds_client_init
#define jaglink_uds_client_reset link_uds_client_reset
#define jaglink_uds_client_begin link_uds_client_begin
#define jaglink_uds_client_accept link_uds_client_accept
#define jaglink_uds_client_tick link_uds_client_tick

#ifdef __cplusplus
}
#endif

#endif
